# Generated by Django 3.2.8 on 2021-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='entries/'),
            preserve_default=False,
        ),
    ]
